### ISSUE TITLE
Dans une fiche SILL, ajouter un champ "Informations générales" pour les tutoriels, etc.

### ISSUE THREAD

**Issue by bzg** [etalab/sill-web#10]

**Comment by bzg** [comment]
Il me semble que cette issue peut être fermée.

**Comment by garronej** [comment]
Tu penses?  
Je pensais au contraire que c'était une priorité.  
De pouvoir laisser aux référents la liberté de renseigner des informations diverse dans un champ plus libre.  
Je pensais notamment que ça pouvait permettre de faire d'une pierre deux coups avec: 
https://github.com/etalab/sill-web/issues/55

Ce que je voyais c'est permettre aux gens de rentrer du Markdown (avec des liens ect) et de le render en HTML sur la fiche.

**Comment by bzg** [comment]
Je ne suis pas trop pour le markdown dans le contenu: est-ce utile ?  Par contre, détecter les URL pour les rendre cliquables, c'est bien.

**Comment by garronej** [comment]
> Je ne suis pas trop pour le markdown dans le contenu: est-ce utile ? 

Le markdown permettrait au référent de mettre en forme comme ils veulent les informations complémentaires.  
Ils pourront mettre des images, des gifs, créer des titres, formater des liens.  

Je me disais que ça pourrait faire comme une sorte de README pour les fiches SILL.  

Pour moi il n'y a aucun downside... peux-tu m'expliquer ton point de vue?

**Comment by garronej** [comment]
It's done 🚀

<img width="1306" alt="image" src="https://user-images.githubusercontent.com/6702424/193634756-2068e313-ac3f-48eb-8743-7b6d1fd54d79.png">

<img width="1313" alt="image" src="https://user-images.githubusercontent.com/6702424/193634950-da9b5c3b-980e-4e9f-9e75-ff365b128bad.png">

https://sill.etalab.gouv.fr/software?name=Keycloakify

**Comment by bzg** [comment]
Top, merci !
