### ISSUE TITLE
Indiquer quel est le problème résolu par cette application

### ISSUE THREAD

**Issue by garronej** [etalab/sill-web#104]
Transfert of [this issue](https://github.com/etalab/sill-docs/issues/6%23issue-1375395628)

**Comment by garronej** [comment]
@bzg done: https://github.com/etalab/sill-docs/blob/main/README.md  

C'est pas de la grande litérature mais bon.

**Comment by bzg** [comment]
Vu, je me note de relire, je ferai les changements directement si c'est OK pour toi.  Merci !

**Comment by bzg** [comment]
J'ai fait une passe sur le `README` - n'hésite pas à me dire si tu as des remarques.
