### ISSUE TITLE
Mettre le bon lien vers la documentation après "Cliquez ici"

### ISSUE THREAD

**Issue by bzg** [etalab/sill-web#105]
![Screenshot 2022-09-18 at 21-51-27 Socle interministériel de logiciels libres ](https://user-images.githubusercontent.com/63500/190925778-9f70b3a7-9a8b-408e-8fc1-1c4b5aeebcaa.png)

Le lien renvoie actuellement vers GitBook - il faudrait soit remettre https://man.sr.ht/~etalab/logiciels-libres/sill.md soit mettre un lien vers la page telle qu'affichée dans l'application.

**Comment by garronej** [comment]
Now yes ^^  
https://github.com/etalab/sill-web/blob/63351fbb204a58f60cb3e196b2b0a513a95f1cbb/src/ui/components/pages/Readme.tsx#L10  

SourceHut won't let me download the raw content from the client so as use the server as a proxy.  

Anyway you can try it out, it's synced in real time.  :)

**Comment by garronej** [comment]
Je ferme pour m'y retrouver, mais n'hésite pas à rouvrir si tu as des remarques

**Comment by bzg** [comment]
Aucune remarque, je testerai, c'est top !
