### ISSUE TITLE
Distinguer le déréférencement de la suppression

### ISSUE THREAD

**Issue by bzg** [etalab/sill-web#115]
Pour une entrée du SILL qui est ajoutée par erreur, il faut pouvoir la supprimer entièrement plutôt que la déréférencer.

Voir par exemple Xmind, qui aurait dû être supprimé plutôt que déréférencé.

**Comment by garronej** [comment]
Es que ce n'est pas kkchose qu'on peut modérer en étant attentif à ce qui se passe sur sill-data?

**Comment by bzg** [comment]
Pour l'instant oui, même si moi-même je ne suis pas à l'aise avec la procédure de suppression: tu peux la rappeler ici ? 

En imaginant qu'on ait un jour un statut "modérateur" via l'interface du SILL, ceux-ci devront pouvoir avoir le choix entre "déréférencer" et "supprimer".

**Comment by garronej** [comment]
Salut Bastien,  

J'ai fait une video pour montrer, de manière pratique, comment on pouvais supprimer une entrée:  

https://filedn.com/lYPEPucNMheV19aDu23lK0Q/Etalab/manually%20remove%20an%20entry%20from%20the%20SILL.mov  

En résumé:  

```bash
git clone https://github.com/etalab/sill-data
cd sill-data
git rebase -i HEAD~20
# Remplacer `pick` par un `d` devant les commit qu'on souhaite supprimer. Sauvegarder et quitter.
git push -f
```

**Comment by bzg** [comment]
Merci !  C'est toujours utile d'avoir cette approche par réécriture de l'historique Git sur `sill-data`, notamment parce que ça permet d'être conforme RGPD quand un agent public demande à ne plus _du tout_ figurer dans la base.

En attendant que ce soit implémentable depuis l'UI, je propose qu'on distingue entre les déréférencements liés à des **erreurs d'ajout** et ceux liés à une sortie ordinaire du SILL (i.e. pour d'autres raisons que des erreurs d'ajout).

C'est nécessaire pour ne pas du tout faire apparaître les erreurs d'ajout dans [ce tableau](https://code.gouv.fr/data/sill.md), par exemple.

On pourrait s'appuyer (temporairement) sur la raison du déréférencement, mais c'est un peu flacky.  Peut-être une checkbox dans le déréférencement pour indiquer que ça doit être considéré comme une suppression?

**Comment by garronej** [comment]
Done!  

https://user-images.githubusercontent.com/6702424/197102029-38455422-cf98-4ccc-aaa6-7983b9c0b864.mov

**Comment by bzg** [comment]
Génial, merci !
