### ISSUE TITLE
Implémenter un export PDF, même rudimentaire

### ISSUE THREAD

**Issue by bzg** [etalab/sill-web#12]
Peut-être que ça ne passe pas par l'application mais par un script (via GitHub Actions?) qui va prendre le `json` et proposer une liste en PDF des logiciels du SILL.

**Comment by garronej** [comment]
PDR Obligatoir donc?  
Je ne peut pas réutiliser ton download as CSV?

**Comment by bzg** [comment]
Mettons ça en pause pour l'instant, je vais voir si je peux générer le PDF depuis le CSV moi-même.

**Comment by garronej** [comment]
Ce n'est pas pour te rajouter du travail, je vois juste les issues s'accumuler, je te laisse voir comment tu veux que je pondère mes priorités.

**Comment by bzg** [comment]
J'ai noté de faire ça côté code.gouv.fr, je supprime d'ici.

**Comment by bzg** [comment]
Fait depuis hier: https://code.gouv.fr/data/sill.pdf
