### ISSUE TITLE
Ajouter la possibilité de définir un lien pour chaque logiciel

### ISSUE THREAD

**Issue by camillemonchicourt** [etalab/sill-web#131]
Pour mentionner un lien vers son site officiel de présentation, de démonstration, de documentation, de téléchargement.

**Comment by garronej** [comment]
Bonjour @camillemonchicourt,  

Il y a pour l'instant un champ libre en Markdown qui permet de renseigné des champs arbitraires.  
Cela ne correspondrait-il pas au besoin?  

Example:
https://sill.etalab.gouv.fr/software?name=Dolibarr

**Comment by camillemonchicourt** [comment]
Oui, en effet j'ai utilisé le texte général de présentation pour ajouter un lien : https://sill.etalab.gouv.fr/software?name=Geotrek

Mais je vois justement sur la page de Dolibarr qu'elle dispose d'un champs dédié pour le lien vers le site et un pour le code source : 

![image](https://user-images.githubusercontent.com/4418840/219865505-ad485000-597f-4d79-bac4-e6f5b5349541.png)

Je n'ai pas cela quand j'accède au formulaire de https://sill.etalab.gouv.fr/software?name=Geotrek

**Comment by garronej** [comment]
Ah d'accord,  
En fait il y a un certain nombre d'informations, notamment le logo, qui sont récupéré de la fiche wikidata du logiciel.  
https://www.wikidata.org/wiki/Q2076540  
Si vous crée une fiche wikidata pour Geotrek la fiche SILL sera automatiquement enrichie.

**Comment by camillemonchicourt** [comment]
OK j'ai fait ça - https://sill.etalab.gouv.fr/software?name=Geotrek
Merci.

**Comment by garronej** [comment]
Merci d'avoir remplis la fiche avec tant de soins!  

![image](https://user-images.githubusercontent.com/6702424/219881696-abd48e85-5754-4b5f-9423-fa85e9981c7c.png)
