### ISSUE TITLE
Implémenter la liste des services et la possibilité d'ajouter des services

### ISSUE THREAD

**Issue by bzg** [etalab/sill-web#14]
Pour (bien) plus tard (version 2 ?): ne pas oublier ce chantier (l'ex-PAPILLON).

**Comment by garronej** [comment]
Je peut enfin ferme cette issue 🎉

https://filedn.com/lYPEPucNMheV19aDu23lK0Q/Etalab/Screen%20Recording%202022-10-21%20at%2000.11.57.mov

**Comment by bzg** [comment]
Beau boulot, merci beaucoup !

**Comment by garronej** [comment]
Merci, avec plaisir!
