### ISSUE TITLE
Fautes d’orthographe

### ISSUE THREAD

**Issue by pagiraud** [etalab/sill-web#20]
Bonjour,
Je viens de consulter la fiche de présentation d’un logiciel du SILL et sur la page j’ai trouvé plus de 10 fautes d’orthographe (j’ai arrêté de compter). Je pense qu’une petite relecture s’impose…
Salutations,

**Comment by bzg** [comment]
Bonjour, merci d'avoir relu !

Nous devons effectivement faire une passe de relecture sur les éléments d'interface de ce dépôt, nous sommes dessus.

**Comment by bzg** [comment]
Ca devrait aller mieux : est-ce que vous confirmez ?

Il peut rester des fautes dans le contenu de certains champs : c'est dû au fait que le SILL récupère une partie des données depuis Wikidata.  Si les fautes sont dans les contenus Wikidata, il faut les corriger en amont.  N'hésitez pas à nous signaler dans cette issue les coquilles que vous trouveriez encore.

Merci !

**Comment by garronej** [comment]
Merci beaucoup

**Comment by pagiraud** [comment]
Merci, c’est beaucoup mieux en effet. Quelques erreurs subsistent à mon avis : 
 Identifiant unique dans la base de donnée**s** des logiciels du SILL~~.~~
Date d'entrée dans le ~~sill~~**SILL**
Licen~~s~~**c**e
 S'agit-il d'un logiciel s'installant directement sur le poste de l'agent (exemple: LibreOffice, contre-exemple: WordPress) **?**
Wikidata est une base de connaissance**s** collaborative et libre
