### ISSUE TITLE
Ignorer les accents dans la recherche

### ISSUE THREAD

**Issue by bzg** [etalab/sill-web#21]
Une recherche avec "vidéo" et "video" devrait retourner les mêmes résultats.

"vidéo" permet de trouver Esup-Pod, mais "video" non.

Voir [ce bout de code](https://git.sr.ht/~etalab/sill.etalab.gouv.fr/tree/master/item/src/cljs/sillweb/core.cljs#L162) de l'ancien site.

**Comment by garronej** [comment]
Yes bien vu je patch tout de suite
