### ISSUE TITLE
Offrir la possibilité de se connecter avec AgentConnect

### ISSUE THREAD

**Issue by micedre** [etalab/sill-web#25]
Vu que l’accès au SILL est autorisé à tous les agents de la fonction public, il me semble pertinent de rajouter une possibilité de connexion par [AgentConnect](https://agentconnect.gouv.fr/). Egoistement, cela m'éviterait aussi de devoir créer un n-ieme compte :) 

L'extension de l'Insee pourrait être utile : https://github.com/InseeFr/Keycloak-FranceConnect

**Comment by garronej** [comment]
Tkt Cédrique,  
C'est prévu dans les plus bref délais.  
J'en fait une pub a la limite du forçage pour ton extension. 😉

**Comment by bzg** [comment]
Fait ! Merci :)
