### ISSUE TITLE
Dire aux utilisateurs n'utilisant pas Javascript où ils peuvent trouver les données du SILL

### ISSUE THREAD

**Issue by bzg** [etalab/sill-web#29]
Par exemple `~$ lynx https://code.gouv.fr` affiche ce message:

    We do understand why you might not want to use Javascript.
    To access to the data exposed in this website, please refer to its repository.

    Nous comprenons bien pourquoi vous ne souhaitez pas utiliser de Javascript.
    Pour accéder aux données exposées via ce site web, merci de vous référer à ce dépôt.

Une balise `<noscript>` dans le `index.html` suffirait.

Le texte peut pointer vers code.gouv.fr/data/sill/json/all.json et code.gouv.fr/data/sill/csv/all.csv qui existeront bientôt.

**Comment by garronej** [comment]
Bonne idée! D'ailleur j'ai reporter ton noscript il faut que je le retire

**Comment by garronej** [comment]
Il faut attendre que le gros refactor soit en ligne mais c'est bon:  

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/6702424/180734769-559bed1b-3cde-43bd-bb1d-112a185ef3f9.png">

J'ai calqué sur code.gouv.fr

**Comment by bzg** [comment]
Je suggère de renvoyer à ce lien : https://code.gouv.fr/data/sill-data.json

C'est aussi celui que nous indiquons sur https://code.gouv.fr/#/about

**Comment by garronej** [comment]
En fait j'essaie de rendre le SILL "self contained".  
Je suis à fond sur la documentation technique, je fais en sorte que le sill soit instanciable indépendamment et qu'il soit plaforme agnostique.  
Un lien en dur vers le catalogue officiel ne s'inscrit pas dans cette logique.  
D'ailleurs est-ce que ça va si j'arrête de te poser le fichier en SSH et que tu viens le récupéré sur https://sill.etalab.gouv.fr/api/sill.json qui reflète toujours la dernière version ?  
Es que tu as besoin d'un événement quand il y a une mise à jour?

**Comment by bzg** [comment]
OK pour l'orientation du catalogue vers une application *self-contained* - il faudra songer à ne pas appeler l'application "SILL", pour ne pas "hardcoder" avec le contenu.

OK pour utiliser l'URL du `json` que tu m'as envoyé: tu pourras couper l'upload de `sill-data.json` quand j'aurai mis à jour le frontend de `code.gouv.fr` (je te préviendrai dans ce fil).  Pas besoin d'événement quand il y a une mise à jour.

**Comment by bzg** [comment]
PS: https://sill.etalab.gouv.fr/api/sill.json renvoie une erreur.

**Comment by garronej** [comment]
> PS: https://sill.etalab.gouv.fr/api/sill.json renvoie une erreur.   

Oui ce n'es pas encore en production, j'ai fait un gros refactor, je doit résoudre différent problèmes de build.  
Je te fais signe dès que c'est UP.

**Comment by bzg** [comment]
> Je te fais signe dès que c'est UP.

Ça marche,merci !
