### ISSUE TITLE
Préciser si le logiciel référencé est installé par l'établissement ou par l'agent public

### ISSUE THREAD

**Issue by bzg** [etalab/sill-web#33]
Cela implique trois changements:

- quand un utilisateur inscrit veut devenir référent d'un logiciel déjà existant, lui demander s'il veut être référent au nom de son établissement (qui a installé le logiciel) ou en son nom propre (pour un logiciel installé sur son poste par ses soins) ;
- quand un utilisateur inscrit veut référencer un nouveau logiciel, lui poser la même question ;
- pouvoir filtrer la liste principale des références du SILL en fonction de savoir si elles sont référencées par des établissements ou par des agents (qui ont installé le logiciel sur leur machine).

Le changement est assez radical : il signifie qu'on accepte de référencer dans le SILL des logiciels libres installés par les agents, non par les établissements.

Je crois qu'il est admissible si on affiche correctement la distinction entre les deux listes et si les lecteurs du SILL voient la différence.

Qu'est-ce que tu en penses ?

Ce sera aussi à discuter avec tous les référents SILL dans un prochain point.

**Comment by garronej** [comment]
> pouvoir filtrer la liste principale des références du SILL en fonction de savoir si elles sont référencées par des établissements ou par des agents (qui ont installé le logiciel sur leur machine).  

Il manque ça, le reste est fait:  

<img width="280" alt="image" src="https://user-images.githubusercontent.com/6702424/169200831-82b82d4b-8878-4311-a3de-d44892da97b1.png">

**Comment by bzg** [comment]
Ne faut-il pas fermer cette issue ?

**Comment by garronej** [comment]
Je l'avais laisser ouverte parce que je n'ai pas fait ça:  

> pouvoir filtrer la liste principale des références du SILL en fonction de savoir si elles sont référencées par des 
> établissements ou par des agents (qui ont installé le logiciel sur leur machine).

Mais peut être que ça peut faire l'objet d'une autre issue...
