### ISSUE TITLE
Rendre tos_fr.md affichable plutôt que téléchargeable

### ISSUE THREAD

**Issue by bzg** [etalab/sill-web#35]
https://sill.etalab.gouv.fr/tos_fr.md n'affiche pas les CGU mais télécharge le fichier.

Il faudrait afficher les CGU.

**Comment by garronej** [comment]
Oui tu as raison,  

A noter, les TOS sont afficher rendered a tout les utilisateur au moment de l'inscription.  

https://user-images.githubusercontent.com/6702424/168471437-0401441c-998d-4c1e-a375-72e4504ff4a0.mov

**Comment by bzg** [comment]
Oui, mais pour le coup je trouve cet affichage trop intrusif - je vais faire une autre proposition et réoganiser les issues.

**Comment by garronej** [comment]
Done!  
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/6702424/179516140-340b3135-85a1-4133-8453-40059ebba573.png">
