### ISSUE TITLE
Pour les logiciels qui sont des modules d'autres logiciels, indiquer le logiciel parent

### ISSUE THREAD

**Issue by bzg** [etalab/sill-web#38]
Par exemple, pour [Escalation](https://sill.etalab.gouv.fr/catalogue?search=escal), la vue principale devrait donner un indice du fait qu'il s'agit d'un module de GLPI.

(Le sujet de l'inclusion des modules dans le SILL est un sujet à part entière, mais au moins cet affichage sera un progrès.)

**Comment by garronej** [comment]
ça marche!  
Au passage, c'est dors et déjà dans la fiche principale. 

<img width="430" alt="image" src="https://user-images.githubusercontent.com/6702424/169200385-636687d4-65dd-4b18-a223-11d1083bb1d7.png">
