### ISSUE TITLE
Dans la page principale, permettre aux référents d'éditer la fiche directement

### ISSUE THREAD

**Issue by bzg** [etalab/sill-web#39]
Pour l'instant, il faut cliquer sur "En savoir plus", puis "Mettre à jour la fiche SILL de ce logiciel".

Il faudrait pouvoir éditer une fiche directement depuis la page principale.

**Comment by garronej** [comment]
<img width="535" alt="image" src="https://user-images.githubusercontent.com/6702424/171199362-a6182b35-73cd-4640-beb1-cfc704fd5329.png">
<img width="528" alt="image" src="https://user-images.githubusercontent.com/6702424/171199388-ad428d1e-4764-472f-98e3-cd3a74e7e071.png">
Done!

**Comment by bzg** [comment]
Génial, merci !
