### ISSUE TITLE
Indiquer à ceux qui veulent s'inscrire de nous contacter si leur nom de domaine n'est pas dans la liste blanche

### ISSUE THREAD

**Issue by bzg** [etalab/sill-web#4]

**Comment by bzg** [comment]
Voir https://github.com/etalab/noms-de-domaine-organismes-publics pour une liste de noms de domaine du secteur public.

**Comment by garronej** [comment]
<img width="326" alt="image" src="https://user-images.githubusercontent.com/6702424/162418649-1ecab1f2-a404-43ed-8cbf-fbcd7fb7efec.png">

**Comment by bzg** [comment]
Cool - attention à l'espace manquante après le "à" : `à:logiciels...`.

**Comment by garronej** [comment]
Ah oui merci!!!
