### ISSUE TITLE
Dans une fiche SILL, permettre d'éditer les champs "similaire à" et "alternative à"

### ISSUE THREAD

**Issue by bzg** [etalab/sill-web#40]
`similaire à` doit renvoyer à d'autres logiciels du SILL.

`alternative à` renvoie à des logiciels propriétaires aux fonctionnalités équivalentes.

A la recherche, tenir compte du champ `alternative à`: un utilisateur qui cherche "Office365" ou "Word" doit pouvoir tomber sur la fiche de LibreOffice.

**Comment by garronej** [comment]
**enfin**  

https://user-images.githubusercontent.com/6702424/178438644-a395a922-f12a-443c-b6cc-437e18edaff9.mov

Après on peut chercher `photoshop` et trouver Gimp

J'ai vraiment galéré à implémenter cette feature pfiou...

**Comment by bzg** [comment]
Joseph Garrone ***@***.***> writes:

> J'ai vraiment galéré à implémenter cette feature pfiou...

C'est top, merci !  On va pouvoir lancer un appel à contribution sur ce point précis une fois qu'on aura décidé de la bonne façon de contacter tous les référents SILL.
