### ISSUE TITLE
Supprimer le suivi via AT Internet

### ISSUE THREAD

**Issue by bzg** [etalab/sill-web#42]

**Comment by garronej** [comment]
Je n'ai pas compris...

**Comment by bzg** [comment]
Done :)

**Comment by garronej** [comment]
OK désolé si j'avais fait n’importe quoi 😄

**Comment by bzg** [comment]
Non, non, c'était une obligation, ça ne l'est plus depuis peu !  Les modules de blocage des trackers dans Firefox/Chromium vont pouvoir cesser de clignoter, c'est une bonne chose.
