### ISSUE TITLE
Optimiser la taille des fichiers .js transférés?

### ISSUE THREAD

**Issue by bzg** [etalab/sill-web#44]
Par exemple https://sill.etalab.gouv.fr/static/js/2.19dcaa0b.chunk.js fait 2.24 MO en taille et transfert.

Est-ce que le serveur peut compresser les fichiers .js au moment du transfert, comme avec nginx/gzip ou [brotli](https://github.com/google/brotli)?

**Comment by garronej** [comment]
Voilà,  
C'etais le message que je craignais.  
Les SPA on beaucoup d'avantages mais le bundle size deviens vite un problème.  
Je prend la journée pour voir ce que je peut faire, nottement en activant le lazy fetching.

**Comment by garronej** [comment]
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/6702424/172060330-fe080e84-8db8-42f7-969e-da51c0dd43c7.png">

- [ ]: Télécharger les fichiers de langues Keycloak au besoin
- [ ]: Arreter d'utiliser moment.js au profit d'API built in
- [ ]: C'est pas worth d'avoir une polyfill pour normalize (retirer unorm)
- [ ]: Tant pis, pas de support de commentaire dans le json de config, supprimer esprima.  

Déjà avec ça on gagne 20%, ensuite je peut activer gzip

**Comment by bzg** [comment]
> Déjà avec ça on gagne 20%, ensuite je peut activer gzip

Avec gzip tu gagneras plus.  C'est top si tu peux optimiser un peu, mais n'y passe pas trop de temps (surtout le week-end !), ce n'est pas un point bloquant.

**Comment by garronej** [comment]
![image](https://user-images.githubusercontent.com/6702424/172077256-34723870-a6cf-473f-8856-45551a53a1fd.png)

🎉

**Comment by garronej** [comment]
PS: J'ai activer sur le serveur aussi

**Comment by bzg** [comment]
![sill](https://user-images.githubusercontent.com/63500/172105947-143d1afb-ff9a-422e-b0e2-b8794fb4f421.png)

Tu as une idée de pourquoi le plus gros `.js` ne semble pas compressé? Il l'est déjà en amont? Tu as activé `gzip` pour `application/javascript`?

**Comment by garronej** [comment]
😕 J'ai même pas vérifier que ça marchais effectivement, c'est pas bien.   
Non en effet j'ai copier coller un truck sur internet mais il n'y avais pas le bon content type dans la liste.  
https://github.com/etalab/sill-web/blob/78578622e522fffe2d642e6411f43d24da52fd61/nginx.conf%23L8

**Comment by bzg** [comment]
C'est beaucoup mieux comme ça!  Je ferme l'issue, merci beaucoup.

**Comment by garronej** [comment]
Merci à toi franchement!

**Comment by garronej** [comment]
Toutes les instances d'Onyxia vont prendre un instance boost graçe a toi!
