### ISSUE TITLE
Permettre de revenir au site depuis la page authentification

### ISSUE THREAD

**Issue by FrancoisSchnell** [etalab/sill-web#49]
Si un utilisateur clique sur l'icone d'authentification ou sur "référencer un nouveau logiciel" en étant pas authentifié, il ne semble pas y avoir de moyen de revenir en arrière (en fermant la croix de la box "connexion" ou flèche retour du navigateur).

**Comment by garronej** [comment]
Salut François,  
Merci pour l'issue! Je peut reproduire

**Comment by garronej** [comment]
C'est corriger, merci pour le rapport @FrancoisSchnell!
