### ISSUE TITLE
Ajout colonne `post_agent` avec picto (ordi + téléphone)

### ISSUE THREAD

**Issue by bzg** [etalab/sill-web#5]
Cf. https://git.sr.ht/~etalab/sill/blob/master/sill.csv

**Comment by garronej** [comment]
<img width="1236" alt="image" src="https://user-images.githubusercontent.com/6702424/162173743-d18e1a5b-8b9c-4cba-b7cc-0842e32c0525.png">

**Comment by bzg** [comment]
s/Installé/À installer ?

**Comment by garronej** [comment]
Oui tu as raison, je vais opérer au changement.

**Comment by garronej** [comment]
Done

**Comment by garronej** [comment]
<img width="582" alt="image" src="https://user-images.githubusercontent.com/6702424/162201031-96fcab49-d037-4c7b-9d07-d6e7d9b480c8.png">
