### ISSUE TITLE
Publier des informations sur les communautés existantes pour les logiciels

### ISSUE THREAD

**Issue by bzg** [etalab/sill-web#55]
Avec un focus sur les communautés francophones et orientées "agents publics".

Extrait du CR de la réunion du 27 juin 2022:

> Dans un premier temps, nous convenons de partir sur une page web qui présente les ressources communautaires (francophones? orientées agents publics ?) autour des logiciels du SILL.

**Comment by garronej** [comment]
Je pense ferme ça car je crois que ça peut rentrer dans #10, n'hésite pas à rouvrir si tu n'es pas d'accord
