### ISSUE TITLE
Afficher l'année dans la date indiquée dans une fiche SILL

### ISSUE THREAD

**Issue by bzg** [etalab/sill-web#69]
![Screenshot 2022-07-27 at 16-06-51 Socle interministériel de logiciels libres ](https://user-images.githubusercontent.com/63500/181268070-ad13c869-c9ce-4d5c-ac43-fd1f086b70fd.png)

On ne sait pas si c'est `Jeudi 24 mars` de 2022, 2021, etc.

**Comment by bzg** [comment]
Fait! Merci.

**Comment by bzg** [comment]
Je rouvre car les années ne s'affichent pas pour toutes les entrées: https://sill.etalab.gouv.fr/software?name=R

**Comment by bzg** [comment]
Je fais remonter cette issue, s'il y a moyen de corriger pour toutes les entrées.

Par exemple https://sill.etalab.gouv.fr/software?name=opendcim n'affiche toujours pas l'année.

**Comment by bzg** [comment]
Un commentaire test depuis Emacs!

**Comment by bzg** [comment]
Un commentaire depuis Emacs!

**Comment by garronej** [comment]
Done

<img width="736" alt="image" src="https://user-images.githubusercontent.com/6702424/197073869-15df13a5-0f52-49d8-aae9-90b3d599a781.png">
