### ISSUE TITLE
Permaliens rétro-compatibles ?

### ISSUE THREAD

**Issue by bzg** [etalab/sill-web#7]
Hello, aujourd'hui le site du SILL propose des permaliens du genre https://sill.etalab.gouv.fr/fr/software?id=6

La nouvelle solution propose des permaliens du genre https://sill.garronej.dev/catalogue?softwareName=LibreOffice

Vaut-il la peine de tenter des redirections côté application pour que les anciens permaliens redirigent vers les nouveaux?

**Comment by garronej** [comment]
Is has been implemented with frontend routing.  (...deploying) 

https://sill.garronej.dev/fr/software?id=6  

The locale is even respected.  
If you hit 

https://sill.etalab.gouv.fr/en/software?id=6

you'll get it in English

**Comment by bzg** [comment]
Great, thanks a lot!
