### ISSUE TITLE
Ajouter un lien vers le flux RSS de code.gouv.fr

### ISSUE THREAD

**Issue by bzg** [etalab/sill-web#8]
Le site actuel du SILL propose un flux RSS avec les derniers changements du SILL: https://sill.etalab.gouv.fr/updates.xml

Avant d'être en production, le nouveau SILL doit offrir une fonctionnalité équivalente.

**Comment by garronej** [comment]
Ca marche

**Comment by bzg** [comment]
Le flux RSS sera accessible via code.gouv.fr.

**Comment by bzg** [comment]
Le lien sur code.gouv.fr : https://code.gouv.fr/data/latest-sill.xml

**Comment by bzg** [comment]
Je ne vois pas le lien https://code.gouv.fr/data/latest-sill.xml dans le diff, mais https://sill.etalab.gouv.fr/updates.xml - est-ce que tu as bien mis `latest-sill.xml`?
