### ISSUE TITLE
Pour les logiciels déréférencés, ajouter la date de déréférencement dans la fiche détaillée

### ISSUE THREAD

**Issue by bzg** [etalab/sill-web#81]
Par exemple pour ce [logiciel](https://sill.etalab.gouv.fr/software?name=Squash%20TF), on ne voit pas quand il a été déréférencé.

**Comment by garronej** [comment]
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/6702424/197072624-8a83578e-a617-493e-a199-acd1d4ea3716.png">

Afficher relativement ça te va?

**Comment by bzg** [comment]
Oui, c'est encore mieux, à condition qu'on ait aussi la date de déréférencement en absolu: peut-être ajouter une ligne après la "Date d'entrée dans le SILL" qui indique la "Date de déréférencement" ?

A noter que les entrées supprimées (vs. déréférencées) ne devraient pas avoir l'URL fonctionnelle pointant vers une fiche.

**Comment by garronej** [comment]
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/6702424/197103700-f796e0dd-1800-496a-a990-c643e0119a39.png">

Alors voilà, c'est moi gimicky que d'afficher un temps relatif.

**Comment by bzg** [comment]
Fair enough, merci !
