### ISSUE TITLE
Réintroduire :versionMax ?

### ISSUE THREAD

**Issue by bzg** [etalab/sill-web#83]
L'ancienne version du SILL (circa 2021) avait une notion de « version maximale », qui est la dernière version recommandable quand un logiciel sort du SILL, comme Audacity.

Peut-on rajouter cela comme une propriété à l'intérieur de `dereferencing`?

**Comment by garronej** [comment]
This is done already

**Comment by garronej** [comment]
Maybe dereferenced softwar could still apear in the list somehow.

**Comment by bzg** [comment]
Yes, that's the idea, and that's what is done at the end of the PDF: https://code.gouv.fr/data/sill.pdf
