### ISSUE TITLE
Ajouter les liens vers les publications du SILL aux autres formats

### ISSUE THREAD

**Issue by bzg** [etalab/sill-web#93]
Voir https://code.gouv.fr/#/about pour la liste des formats disponibles.

**Comment by garronej** [comment]
<img width="311" alt="image" src="https://user-images.githubusercontent.com/6702424/197083706-759101e5-a8ba-46ef-8ae6-c3eda1116978.png">

Merci de généré les donée aux autres formats!

**Comment by bzg** [comment]
You're welcome.
