### ISSUE TITLE
Ajouter les prestataires de l'annuaire du CNLL

### ISSUE THREAD

**Issue by bzg** [etalab/sill-web#94]
Cf. https://annuaire.cnll.fr/api/prestataires-sill.json qui contient pour chaque entrée un identifiant SILL.

Comme pour `comptoirDuLibreSoftware`, créer `annuaireCnllSoftware` avec une sous-entrée `providers` contenant la liste des prestataires et pour chaque, juste un champ `url`.

Une fois que cela sera fait, j'ajouterai l'affichage détaillé des prestataires sur code.gouv.fr.

**Comment by bzg** [comment]
J'ai (temporairement) ajout les informations de l'annuaire CNLL aux données produites par `codegouvfr-consolidate-data` et elles sont aussi affichées sur code.gouv.fr (voir par exemple: https://code.gouv.fr/#/sill/52). 

L'idéal serait d'intégrer les données des prestataires Comptoir du libre et CNLL dans le `sill.json` produit de ton côté.

**Comment by garronej** [comment]
Done:  
https://github.com/etalab/sill-api/blob/14aeb464dc1585b832e5c7d03da93ca2f526e2ef/src/model/types.ts#L193-L199

**Comment by bzg** [comment]
Well done!
