### ISSUE TITLE
Erreur à la mise à jour d'un logiciel

### ISSUE THREAD

**Issue by hjonin** [etalab/sill-web#98]
Il semble y avoir une erreur à la mise à jour d'un logiciel (clic sur le bouton d'édition).
Par exemple, pour le logiciel d'ID SILL 320, l'erreur suivante dans la console : "Cannot read properties of undefined (reading 'map')".

**Comment by hjonin** [comment]
Probablement lié à https://github.com/etalab/sill-web/issues/80 :)

**Comment by garronej** [comment]
Damn it took me several hours to fix. Thanks for reporting.
